# Generated by Django 5.2.3 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0003_scan_image_height_scan_image_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="model_scores",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
