# Generated by Django 5.2.3 on 2026-09-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_scan_provenance_multimodal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='label',
            field=models.CharField(choices=[('real', 'Real'), ('ai_generated', 'AI-generated'), ('possibly_ai', 'Possibly AI')], max_length=20),
        ),
    ]
